{{- if .Values.ingress.enabled -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
      - {{ pluck (.Values.global.env | default "default") .Values.certificate.dnsName | first | toString }}
      secretName: {{ .Values.certificate.secretName }}
  rules:
    - host: {{ pluck (.Values.global.env | default "default") .Values.certificate.dnsName | first | toString }}
      http:
        paths:
          - path: {{ .Values.ingress.urlPath }}
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.certificate.tlsPort }}
{{- end }}

