# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches:
      - devel
  release:
    types: [ published ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.stkr.io
          username: ${{ secrets.STAKEFI_HARBOR_USERNAME }}
          password: ${{ secrets.STAKEFI_HARBOR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: "./docker/Dockerfile"
          push: true
          tags: harbor.stkr.io/stkr/blockscout-explorer:devel