global:
  repository: ankrnetwork
  tag: test
  image: blockscout-gateway
  env: dev
  host: dev.stkr.io

replicaCount: 1
hostNetwork: false
dnsPolicy: ClusterFirst
imagePullPolicy: IfNotPresent

services:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  - protocol: TCP
    port: 6565
    targetPort: 6565

certificate:
  enabled: true
  clusterIssuer: letsencrypt
  dnsName:
    dev: "api-bas.dev.stkr.io"
  secretName: blockscout-gateway-tls
  tlsPort: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/use-regex: "true"
  urlPath: "/"

metrics:
  enabled: false
  port: 7575

#livenessProbe:
#  httpGet:
#    port: 6001
#    path: "/actuator"
#  failureThreshold: 1
#  initialDelaySeconds: 90
#  periodSeconds: 15
#  successThreshold: 1
#  timeoutSeconds: 2
#readinessProbe:
#  httpGet:
#    port: 6001
#    path: "/actuator"
#  failureThreshold: 1
#  initialDelaySeconds: 15
#  periodSeconds: 15
#  successThreshold: 1
#  timeoutSeconds: 2

configMap:
  TEST_ENV: test

